coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "src/RcppExports.cpp"
  - "R/RcppExports.R"
  - "inst/include/**"
