// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_joint_objective
NumericVector compute_joint_objective(const NumericVector& params, const List& data_list, const NumericMatrix& random_effects, const List& parameters, Nullable<NumericVector> weights, bool gradient, bool hessian);
RcppExport SEXP _JointODE_compute_joint_objective(SEXP paramsSEXP, SEXP data_listSEXP, SEXP random_effectsSEXP, SEXP parametersSEXP, SEXP weightsSEXP, SEXP gradientSEXP, SEXP hessianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const List& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type random_effects(random_effectsSEXP);
    Rcpp::traits::input_parameter< const List& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_joint_objective(params, data_list, random_effects, parameters, weights, gradient, hessian));
    return rcpp_result_gen;
END_RCPP
}
// compute_joint_logpost
NumericVector compute_joint_logpost(const NumericVector& random_effect, const List& data, const List& parameters, bool gradient, bool hessian);
RcppExport SEXP _JointODE_compute_joint_logpost(SEXP random_effectSEXP, SEXP dataSEXP, SEXP parametersSEXP, SEXP gradientSEXP, SEXP hessianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type random_effect(random_effectSEXP);
    Rcpp::traits::input_parameter< const List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const List& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< bool >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_joint_logpost(random_effect, data, parameters, gradient, hessian));
    return rcpp_result_gen;
END_RCPP
}
// compute_joint_logpost_batch
NumericVector compute_joint_logpost_batch(const NumericMatrix& samples, const List& data, const List& parameters);
RcppExport SEXP _JointODE_compute_joint_logpost_batch(SEXP samplesSEXP, SEXP dataSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const List& >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_joint_logpost_batch(samples, data, parameters));
    return rcpp_result_gen;
END_RCPP
}
// compute_joint_state
NumericVector compute_joint_state(const NumericVector& initial_state, const List& data, const NumericVector& random_effect, const List& parameters, bool gradient, bool hessian);
RcppExport SEXP _JointODE_compute_joint_state(SEXP initial_stateSEXP, SEXP dataSEXP, SEXP random_effectSEXP, SEXP parametersSEXP, SEXP gradientSEXP, SEXP hessianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< const List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type random_effect(random_effectSEXP);
    Rcpp::traits::input_parameter< const List& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< bool >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_joint_state(initial_state, data, random_effect, parameters, gradient, hessian));
    return rcpp_result_gen;
END_RCPP
}
// solve_batch_joint
List solve_batch_joint(const List& data_list, const NumericMatrix& random_effects, const List& parameters);
RcppExport SEXP _JointODE_solve_batch_joint(SEXP data_listSEXP, SEXP random_effectsSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type random_effects(random_effectsSEXP);
    Rcpp::traits::input_parameter< const List& >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_batch_joint(data_list, random_effects, parameters));
    return rcpp_result_gen;
END_RCPP
}
// compute_marginal_objective
NumericVector compute_marginal_objective(const NumericVector& params, const List& data_list, double biomarker_clamp, bool gradient, bool hessian);
RcppExport SEXP _JointODE_compute_marginal_objective(SEXP paramsSEXP, SEXP data_listSEXP, SEXP biomarker_clampSEXP, SEXP gradientSEXP, SEXP hessianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const List& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< double >::type biomarker_clamp(biomarker_clampSEXP);
    Rcpp::traits::input_parameter< bool >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_marginal_objective(params, data_list, biomarker_clamp, gradient, hessian));
    return rcpp_result_gen;
END_RCPP
}
// compute_marginal_state
NumericVector compute_marginal_state(const NumericVector& initial_state, const List& subject_data, const NumericVector& parameters, double biomarker_clamp, bool gradient, bool hessian);
RcppExport SEXP _JointODE_compute_marginal_state(SEXP initial_stateSEXP, SEXP subject_dataSEXP, SEXP parametersSEXP, SEXP biomarker_clampSEXP, SEXP gradientSEXP, SEXP hessianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< const List& >::type subject_data(subject_dataSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< double >::type biomarker_clamp(biomarker_clampSEXP);
    Rcpp::traits::input_parameter< bool >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_marginal_state(initial_state, subject_data, parameters, biomarker_clamp, gradient, hessian));
    return rcpp_result_gen;
END_RCPP
}
// solve_batch_marginal
List solve_batch_marginal(const List& data_list, const NumericVector& parameters, double biomarker_clamp);
RcppExport SEXP _JointODE_solve_batch_marginal(SEXP data_listSEXP, SEXP parametersSEXP, SEXP biomarker_clampSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< double >::type biomarker_clamp(biomarker_clampSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_batch_marginal(data_list, parameters, biomarker_clamp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JointODE_compute_joint_objective", (DL_FUNC) &_JointODE_compute_joint_objective, 7},
    {"_JointODE_compute_joint_logpost", (DL_FUNC) &_JointODE_compute_joint_logpost, 5},
    {"_JointODE_compute_joint_logpost_batch", (DL_FUNC) &_JointODE_compute_joint_logpost_batch, 3},
    {"_JointODE_compute_joint_state", (DL_FUNC) &_JointODE_compute_joint_state, 6},
    {"_JointODE_solve_batch_joint", (DL_FUNC) &_JointODE_solve_batch_joint, 3},
    {"_JointODE_compute_marginal_objective", (DL_FUNC) &_JointODE_compute_marginal_objective, 5},
    {"_JointODE_compute_marginal_state", (DL_FUNC) &_JointODE_compute_marginal_state, 6},
    {"_JointODE_solve_batch_marginal", (DL_FUNC) &_JointODE_solve_batch_marginal, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_JointODE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
