# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.compute_marginal_objective_cppad <- function(params, data_list, gradient = TRUE, hessian = FALSE) {
    .Call(`_JointODE_compute_marginal_objective_cppad`, params, data_list, gradient, hessian)
}

.solve_marginal_ode_cppad <- function(theta, initial, times, covariates) {
    .Call(`_JointODE_solve_marginal_ode_cppad`, theta, initial, times, covariates)
}

.compute_objective_cppad <- function(params, data_list, random_effects, parameters, weights = NULL, gradient = TRUE, hessian = FALSE) {
    .Call(`_JointODE_compute_objective_cppad`, params, data_list, random_effects, parameters, weights, gradient, hessian)
}

.solve_batch_ode_cppad <- function(data_list, random_effects, parameters) {
    .Call(`_JointODE_solve_batch_ode_cppad`, data_list, random_effects, parameters)
}

.compute_logpost_cppad <- function(random_effect, data, parameters, gradient = TRUE, hessian = FALSE) {
    .Call(`_JointODE_compute_logpost_cppad`, random_effect, data, parameters, gradient, hessian)
}
