# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.compute_joint_objective <- function(params, data_list, random_effects, parameters, weights = NULL, gradient = TRUE, hessian = FALSE) {
    .Call(`_JointODE_compute_joint_objective`, params, data_list, random_effects, parameters, weights, gradient, hessian)
}

.compute_joint_logpost <- function(random_effect, data, parameters, gradient = TRUE, hessian = FALSE) {
    .Call(`_JointODE_compute_joint_logpost`, random_effect, data, parameters, gradient, hessian)
}

.compute_joint_logpost_batch <- function(samples, data, parameters) {
    .Call(`_JointODE_compute_joint_logpost_batch`, samples, data, parameters)
}

.compute_joint_state <- function(initial_state, data, random_effect, parameters, gradient = TRUE, hessian = FALSE) {
    .Call(`_JointODE_compute_joint_state`, initial_state, data, random_effect, parameters, gradient, hessian)
}

.solve_batch_joint <- function(data_list, random_effects, parameters) {
    .Call(`_JointODE_solve_batch_joint`, data_list, random_effects, parameters)
}

.compute_marginal_objective <- function(params, data_list, biomarker_clamp = 50.0, gradient = TRUE, hessian = FALSE) {
    .Call(`_JointODE_compute_marginal_objective`, params, data_list, biomarker_clamp, gradient, hessian)
}

.compute_marginal_state <- function(initial_state, subject_data, parameters, biomarker_clamp = 50.0, gradient = TRUE, hessian = FALSE) {
    .Call(`_JointODE_compute_marginal_state`, initial_state, subject_data, parameters, biomarker_clamp, gradient, hessian)
}

.solve_batch_marginal <- function(data_list, parameters, biomarker_clamp = 50.0) {
    .Call(`_JointODE_solve_batch_marginal`, data_list, parameters, biomarker_clamp)
}
